export type IoIconName =
  | 'api'
  | 'automation'
  | 'build'
  | 'check'
  | 'clock'
  | 'communication'
  | 'consulting'
  | 'content'
  | 'continuity'
  | 'deploy'
  | 'diagnostic'
  | 'handoff'
  | 'scope'
  | 'standard'
  | 'systems';
